# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.fqdn import Fqdn  # noqa: F401,E501
from swagger_server.models.ipv4_addr import Ipv4Addr  # noqa: F401,E501
from swagger_server.models.ipv6_addr import Ipv6Addr  # noqa: F401,E501
from swagger_server.models.port import Port  # noqa: F401,E501
from swagger_server import util


class AccessEndpoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, port: Port=None, fqdn: Fqdn=None, ipv4_addresses: List[Ipv4Addr]=None, ipv6_addresses: List[Ipv6Addr]=None):  # noqa: E501
        """AccessEndpoint - a model defined in Swagger

        :param port: The port of this AccessEndpoint.  # noqa: E501
        :type port: Port
        :param fqdn: The fqdn of this AccessEndpoint.  # noqa: E501
        :type fqdn: Fqdn
        :param ipv4_addresses: The ipv4_addresses of this AccessEndpoint.  # noqa: E501
        :type ipv4_addresses: List[Ipv4Addr]
        :param ipv6_addresses: The ipv6_addresses of this AccessEndpoint.  # noqa: E501
        :type ipv6_addresses: List[Ipv6Addr]
        """
        self.swagger_types = {
            'port': Port,
            'fqdn': Fqdn,
            'ipv4_addresses': List[Ipv4Addr],
            'ipv6_addresses': List[Ipv6Addr]
        }

        self.attribute_map = {
            'port': 'port',
            'fqdn': 'fqdn',
            'ipv4_addresses': 'ipv4Addresses',
            'ipv6_addresses': 'ipv6Addresses'
        }
        self._port = port
        self._fqdn = fqdn
        self._ipv4_addresses = ipv4_addresses
        self._ipv6_addresses = ipv6_addresses

    @classmethod
    def from_dict(cls, dikt) -> 'AccessEndpoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccessEndpoint of this AccessEndpoint.  # noqa: E501
        :rtype: AccessEndpoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def port(self) -> Port:
        """Gets the port of this AccessEndpoint.


        :return: The port of this AccessEndpoint.
        :rtype: Port
        """
        return self._port

    @port.setter
    def port(self, port: Port):
        """Sets the port of this AccessEndpoint.


        :param port: The port of this AccessEndpoint.
        :type port: Port
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def fqdn(self) -> Fqdn:
        """Gets the fqdn of this AccessEndpoint.


        :return: The fqdn of this AccessEndpoint.
        :rtype: Fqdn
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn: Fqdn):
        """Sets the fqdn of this AccessEndpoint.


        :param fqdn: The fqdn of this AccessEndpoint.
        :type fqdn: Fqdn
        """

        self._fqdn = fqdn

    @property
    def ipv4_addresses(self) -> List[Ipv4Addr]:
        """Gets the ipv4_addresses of this AccessEndpoint.

        IP version 4 of an application instance  # noqa: E501

        :return: The ipv4_addresses of this AccessEndpoint.
        :rtype: List[Ipv4Addr]
        """
        return self._ipv4_addresses

    @ipv4_addresses.setter
    def ipv4_addresses(self, ipv4_addresses: List[Ipv4Addr]):
        """Sets the ipv4_addresses of this AccessEndpoint.

        IP version 4 of an application instance  # noqa: E501

        :param ipv4_addresses: The ipv4_addresses of this AccessEndpoint.
        :type ipv4_addresses: List[Ipv4Addr]
        """

        self._ipv4_addresses = ipv4_addresses

    @property
    def ipv6_addresses(self) -> List[Ipv6Addr]:
        """Gets the ipv6_addresses of this AccessEndpoint.

        IP version 6 of an application instance.  # noqa: E501

        :return: The ipv6_addresses of this AccessEndpoint.
        :rtype: List[Ipv6Addr]
        """
        return self._ipv6_addresses

    @ipv6_addresses.setter
    def ipv6_addresses(self, ipv6_addresses: List[Ipv6Addr]):
        """Sets the ipv6_addresses of this AccessEndpoint.

        IP version 6 of an application instance.  # noqa: E501

        :param ipv6_addresses: The ipv6_addresses of this AccessEndpoint.
        :type ipv6_addresses: List[Ipv6Addr]
        """

        self._ipv6_addresses = ipv6_addresses
