# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, code: str=None, message: str=None):  # noqa: E501
        """ErrorInfo - a model defined in Swagger

        :param status: The status of this ErrorInfo.  # noqa: E501
        :type status: int
        :param code: The code of this ErrorInfo.  # noqa: E501
        :type code: str
        :param message: The message of this ErrorInfo.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'status': int,
            'code': str,
            'message': str
        }

        self.attribute_map = {
            'status': 'status',
            'code': 'code',
            'message': 'message'
        }
        self._status = status
        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorInfo of this ErrorInfo.  # noqa: E501
        :rtype: ErrorInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this ErrorInfo.

        HTTP status code returned along with this error response  # noqa: E501

        :return: The status of this ErrorInfo.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ErrorInfo.

        HTTP status code returned along with this error response  # noqa: E501

        :param status: The status of this ErrorInfo.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def code(self) -> str:
        """Gets the code of this ErrorInfo.

        Code given to this error  # noqa: E501

        :return: The code of this ErrorInfo.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ErrorInfo.

        Code given to this error  # noqa: E501

        :param code: The code of this ErrorInfo.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ErrorInfo.

        Detailed error description  # noqa: E501

        :return: The message of this ErrorInfo.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorInfo.

        Detailed error description  # noqa: E501

        :param message: The message of this ErrorInfo.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
