# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.app_manifest import AppManifest  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, app_manifest: AppManifest=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param app_manifest: The app_manifest of this InlineResponse200.  # noqa: E501
        :type app_manifest: AppManifest
        """
        self.swagger_types = {
            'app_manifest': AppManifest
        }

        self.attribute_map = {
            'app_manifest': 'appManifest'
        }
        self._app_manifest = app_manifest

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_manifest(self) -> AppManifest:
        """Gets the app_manifest of this InlineResponse200.


        :return: The app_manifest of this InlineResponse200.
        :rtype: AppManifest
        """
        return self._app_manifest

    @app_manifest.setter
    def app_manifest(self, app_manifest: AppManifest):
        """Sets the app_manifest of this InlineResponse200.


        :param app_manifest: The app_manifest of this InlineResponse200.
        :type app_manifest: AppManifest
        """

        self._app_manifest = app_manifest
