# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.app_id import AppId  # noqa: F401,E501
from swagger_server import util


class SubmittedApp(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, app_id: AppId=None):  # noqa: E501
        """SubmittedApp - a model defined in Swagger

        :param app_id: The app_id of this SubmittedApp.  # noqa: E501
        :type app_id: AppId
        """
        self.swagger_types = {
            'app_id': AppId
        }

        self.attribute_map = {
            'app_id': 'appId'
        }
        self._app_id = app_id

    @classmethod
    def from_dict(cls, dikt) -> 'SubmittedApp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubmittedApp of this SubmittedApp.  # noqa: E501
        :rtype: SubmittedApp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_id(self) -> AppId:
        """Gets the app_id of this SubmittedApp.


        :return: The app_id of this SubmittedApp.
        :rtype: AppId
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id: AppId):
        """Sets the app_id of this SubmittedApp.


        :param app_id: The app_id of this SubmittedApp.
        :type app_id: AppId
        """

        self._app_id = app_id
